<?php
/**
 * Revoked leftovers cannot be read when real filesystem erasure fails.
 *
 * @package Tests\Unit
 * @since 0.5.2
 */

declare(strict_types=1);

use Brain\Monkey\Functions;
use Kntnt\Ai_Visibility\Core\Artifact\Artifact_Registry;
use Kntnt\Ai_Visibility\Core\Artifact\Identity;
use Kntnt\Ai_Visibility\Core\Artifact\Request;
use Kntnt\Ai_Visibility\Core\Cache\Cache_Version;
use Kntnt\Ai_Visibility\Core\Cache\Serve_Router;
use Kntnt\Ai_Visibility\Core\Cache\Single_Flight;
use Kntnt\Ai_Visibility\Core\Content\Content_Matrix;
use Kntnt\Ai_Visibility\Core\Content\Exclusions;
use Kntnt\Ai_Visibility\Core\Eligibility;
use Kntnt\Ai_Visibility\Core\Front_Matter;
use Kntnt\Ai_Visibility\Core\Markdown_Alternate;
use Kntnt\Ai_Visibility\Core\Page_Markdown_Service;
use Kntnt\Ai_Visibility\Core\Plugin_Logger;
use Kntnt\Ai_Visibility\Llms\Index_Builder;
use Kntnt\Ai_Visibility\Llms\Index_Provider;
use Kntnt\Ai_Visibility\Llms\Selected_Types;
use Kntnt\Ai_Visibility\Markdown\Page_Markdown_Provider;

it('refuses leftover files through fresh readers until verified whole-store recovery', function (string $operation): void {
    Functions\when('wp_mkdir_p')->alias(static fn(string $dir): bool => is_dir($dir) || mkdir($dir, 0700, true));
    Functions\when('get_option')->justReturn('/%postname%/');
    Functions\when('wp_json_encode')->alias('json_encode');
    $root = sys_get_temp_dir() . '/kntnt-erasure-' . uniqid('', true);
    $base = $root . '/cache';
    $locks = $root . '/locks';
    mkdir($locks, 0700, true);
    $lines = [];
    $logger = new Plugin_Logger(static function (string $line) use (&$lines): void { $lines[] = $line; });
    $makeStore = static fn() => kntnt_test_file_store(static fn(): string => $base, $logger);
    $store = $makeStore();
    $flight = new Single_Flight($store, $locks);
    $types = new Content_Matrix();
    $eligibility = new Eligibility($types, new Exclusions(fn(): string => '', fn(): string => 'https://example.test'));
    $locator = new Markdown_Alternate();
    $registry = new Artifact_Registry();
    $registry->register(new Page_Markdown_Provider(
        new Page_Markdown_Service(new Front_Matter(), $flight, $logger), $eligibility, $locator,
    ));
    $registry->register(new Index_Provider(
        new Index_Builder($eligibility, new Selected_Types($types, $eligibility), $locator), new Cache_Version(), $locator,
    ));
    $page = new Identity('markdown-alternate', 'revoked', 42);
    $aggregate = new Identity('llms-txt', 'llms-v7', 0);
    $protected = [$base, $base . '/markdown-alternate', $base . '/llms-txt'];
    try {
        expect($store->write($page, 'REVOKED PAGE'))->toBeTrue();
        expect($store->write($aggregate, 'REVOKED AGGREGATE'))->toBeTrue();
        foreach ($protected as $directory) { chmod($directory, 0555); }
        clearstatcache();
        if (is_writable($protected[1])) {
            $this->markTestSkipped('The current user bypasses directory permissions; real unlink failure is required.');
        }
        // Capture native warnings without converting failed unlink into an exception.
        $warnings = [];
        set_error_handler(static function (int $severity, string $message) use (&$warnings): bool {
            if (error_reporting() & $severity) { $warnings[] = $message; }
            return true;
        });
        try {
            $operation === 'delete' ? $store->delete($page) : $store->flush_all();
        } finally {
            restore_error_handler();
        }
        expect(is_file($store->path_for($page)))->toBeTrue();
        $fresh = $makeStore();
        $router = new Serve_Router($fresh, $registry, cache_version: static fn(): int => 7);
        foreach ([[$page, '/revoked.md'], [$aggregate, '/llms.txt']] as [$identity, $path]) {
            expect($fresh->has($identity))->toBeFalse();
            expect($fresh->read($identity))->toBeNull();
            expect($router->resolve(new Request('GET', $path)))->toBeNull();
        }
        expect($warnings)->toBeEmpty();
        expect(implode("\n", $lines))->toContain('Cache erasure failed');
        // Current generated bytes remain usable without trusting or overwriting leftovers.
        $valid = (new Single_Flight($fresh, $locks))->once($page, static fn(): string => 'CURRENT PUBLIC');
        expect($valid->bytes)->toBe('CURRENT PUBLIC');
        expect($valid->persisted)->toBeFalse();
        expect(file_get_contents($store->path_for($page)))->toBe('REVOKED PAGE');
        foreach ($protected as $directory) { if (is_dir($directory)) { chmod($directory, 0700); } }
        $fresh->delete($page);
        expect($makeStore()->read($aggregate))->toBeNull();
        $fresh->flush_all();
        $recovered = $makeStore();
        expect($recovered->write($page, 'CURRENT PUBLIC'))->toBeTrue();
        expect($recovered->read($page))->toBe('CURRENT PUBLIC');
        expect((new Serve_Router($recovered, $registry))->resolve(new Request('GET', '/revoked.md')))->not->toBeNull();
    } finally {
        foreach ($protected as $directory) { if (is_dir($directory)) { chmod($directory, 0700); } }
        if (is_dir($root)) {
            $entries = new RecursiveIteratorIterator(
                new RecursiveDirectoryIterator($root, FilesystemIterator::SKIP_DOTS), RecursiveIteratorIterator::CHILD_FIRST,
            );
            foreach ($entries as $entry) { $entry->isDir() ? rmdir($entry->getPathname()) : unlink($entry->getPathname()); }
            rmdir($root);
        }
    }
})->with(['delete', 'flush']);

it('refuses warm bytes when existing coordination state is truncated or malformed', function (string $broken): void {
    Functions\when('wp_mkdir_p')->alias(static fn(string $dir): bool => is_dir($dir) || mkdir($dir, 0700, true));
    Functions\when('wp_json_encode')->alias('json_encode');
    $root = sys_get_temp_dir() . '/kntnt-erasure-state-' . uniqid('', true);
    $coordination = $root . '/coordination';
    mkdir($coordination, 0700, true);
    $lines = [];
    $logger = new Plugin_Logger(static function (string $line) use (&$lines): void { $lines[] = $line; });
    $makeStore = static fn() => new \Kntnt\Ai_Visibility\Core\Cache\File_Store(
        static fn(): string => $root . '/cache', $logger, $coordination,
    );
    $identity = new Identity('llms-txt', 'llms-v1', 0);
    $types = new Content_Matrix();
    $eligibility = new Eligibility($types, new Exclusions(fn(): string => '', fn(): string => 'https://example.test'));
    $locator = new Markdown_Alternate();
    $registry = new Artifact_Registry();
    $registry->register(new Index_Provider(
        new Index_Builder($eligibility, new Selected_Types($types, $eligibility), $locator), new Cache_Version(), $locator,
    ));
    try {
        expect($makeStore()->write($identity, 'UNTRUSTWORTHY WARM BYTES'))->toBeTrue();
        // Fault injection is confined to this fixture's sole coordination inode.
        $files = glob($coordination . '/*');
        expect($files)->toHaveCount(1);
        file_put_contents($files[0], $broken);
        $fresh = $makeStore();
        expect($fresh->has($identity))->toBeFalse();
        expect($fresh->read($identity))->toBeNull();
        expect($fresh->write($identity, 'REPLACEMENT'))->toBeFalse();
        $router = new Serve_Router($fresh, $registry, $logger);
        expect($router->resolve(new Request('GET', '/llms.txt')))->toBeNull();
        expect(implode("\n", $lines))->toContain('Cache refused');
        expect(fn() => (new Single_Flight($fresh, $coordination))->once($identity, fn(): string => 'CURRENT'))
            ->toThrow(\Kntnt\Ai_Visibility\Core\Cache\Obsolete_Artifact::class);
        expect(file_get_contents($fresh->path_for($identity)))->toBe('UNTRUSTWORTHY WARM BYTES');
    } finally {
        $entries = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($root, FilesystemIterator::SKIP_DOTS), RecursiveIteratorIterator::CHILD_FIRST,
        );
        foreach ($entries as $entry) { $entry->isDir() ? rmdir($entry->getPathname()) : unlink($entry->getPathname()); }
        rmdir($root);
    }
})->with(['', 'invalid', "17\npois", '17', "17\nreadable", "17\npoisoned"]);
