<?php
/**
 * Generated or cached bytes with their independent persistence outcome.
 *
 * @package Kntnt\Ai_Visibility
 * @since 0.5.2
 */

declare( strict_types = 1 );

namespace Kntnt\Ai_Visibility\Core\Cache;

/**
 * Keeps valid generated bytes available when their cache publication fails.
 *
 * A false persistence outcome never denotes a generation error: producers
 * throw on failure. Callers may serve these bytes without reading an older
 * cache file, but must not treat a failed write as successful publication.
 *
 * @since 0.5.2
 */
final readonly class Materialisation {

	/**
	 * Carries the bytes and whether they have an available cache publication.
	 *
	 * @since 0.5.2
	 *
	 * @param string $bytes     The valid cached or freshly generated artifact.
	 * @param bool   $persisted True on a fresh cache hit or successful write.
	 */
	public function __construct( public string $bytes, public bool $persisted ) {}

}
