"""Verify graceful generated-byte serving with a real obstructed cache path.

Usage: python3 tests/Integration/playground-cache-failure.py
KNTNT_CACHE_FAILURE_PORT selects the local port (default 9440).
KNTNT_CACHE_FAILURE_HTTP_BASE probes an existing cache-failure-blueprint site.
KNTNT_SESSION_CLEANUP_SCRIPT optionally registers the local worker for cleanup.
Every Playground worker and its children are stopped on exit.
"""

from http.client import parse_headers
import hashlib
from io import BytesIO
import json
import os
from pathlib import Path
import signal
import socket
import subprocess
import sys
import threading
import time
import urllib.error
import urllib.request
from urllib.parse import urlsplit


def request(base, path, method="GET", headers=None):
    """Read the actual response, retaining deliberate HTTP errors."""
    if method == "HEAD":
        return head_request(base, path, headers or {})
    outgoing = urllib.request.Request(base + path, method=method, headers=headers or {})
    try:
        response = urllib.request.urlopen(outgoing, timeout=30)
    except urllib.error.HTTPError as error:
        response = error
    with response:
        return response.status, response.headers, response.read()


def head_request(base, path, headers):
    """Observe raw HEAD bytes so clients cannot silently discard a leaked body."""
    address = urlsplit(base)
    fields = {"Host": address.netloc, "Connection": "close", **headers}
    outgoing = f"HEAD {path} HTTP/1.1\r\n"
    outgoing += "".join(f"{name}: {value}\r\n" for name, value in fields.items()) + "\r\n"
    with socket.create_connection((address.hostname, address.port), timeout=30) as connection:
        connection.sendall(outgoing.encode("ascii"))
        chunks = []
        while chunk := connection.recv(65536):
            chunks.append(chunk)
    header_block, separator, body = b"".join(chunks).partition(b"\r\n\r\n")
    assert separator, header_block
    status_line, header_fields = header_block.split(b"\r\n", 1)
    return int(status_line.split()[1]), parse_headers(BytesIO(header_fields)), body


def probe(base):
    """Compare unavailable-cache responses with healthy artifact bytes."""
    control = "/?cache_failure_fixture=fixture-only&action="
    runtime = json.loads(request(base, control + "restore")[2])["php"]
    if not runtime.startswith("8.4."):
        raise RuntimeError("Expected actual PHP 8.4, got " + runtime)
    print("Actual Playground PHP " + runtime, flush=True)
    failures = 0

    def check(label, condition):
        """Keep independent failures visible across both real handlers."""
        nonlocal failures
        failures += not condition
        print(("PASS " if condition else "FAIL ") + label, flush=True)

    artifacts = [
        ("/ordinary.md", "text/markdown", {}),
        ("/ordinary/?format=markdown", "text/markdown", {}),
        ("/ordinary/", "text/markdown", {"Accept": "text/markdown"}),
        ("/llms.txt", "text/plain", {}),
        ("/llms-full.txt", "text/plain", {}),
    ]
    expected = {}
    for path, content_type, selection in artifacts:
        status, headers, body = request(base, path, headers=selection)
        check("healthy baseline " + path, status == 200 and headers.get_content_type() == content_type and b"Cache failure fixture" in body)
        expected[path] = body

    for scenario in ["obstruct", "stale"]:
        if scenario == "stale":
            request(base, control + "restore")
            for path, _, selection in artifacts:
                request(base, path, headers=selection)
            request(base, control + "stale")
        else:
            check("fixture really obstructs the cache base", json.loads(request(base, control + "obstruct")[2])["obstructed"])
        for path, content_type, selection in artifacts:
            status, headers, body = request(base, path, headers=selection)
            etag = '"' + hashlib.md5(expected[path]).hexdigest() + '"'
            check(scenario + " cache serves exact generated bytes " + path, status == 200 and headers.get_content_type() == content_type and body == expected[path])
            check(scenario + " cache sends byte length and ETag " + path, headers.get("Content-Length") == str(len(expected[path])) and headers.get("ETag") == etag)
            check(scenario + " cache sends Last-Modified and nosniff " + path, bool(headers.get("Last-Modified")) and headers.get("X-Content-Type-Options") == "nosniff")
            check(scenario + " cache prevents storage " + path, "no-store" in headers.get("Cache-Control", "").lower())
            if content_type == "text/markdown":
                check("Markdown keeps its canonical link " + path, '<' + base + '/ordinary/>; rel="canonical"' in headers.get("Link", ""))
            status, head_headers, body = request(base, path, method="HEAD", headers=selection)
            check(scenario + " cache HEAD keeps GET metadata without a body " + path, status == 200 and body == b"" and head_headers.get_content_type() == content_type and head_headers.get("Content-Length") == str(len(expected[path])) and head_headers.get("ETag") == etag)
            for validator in [
                {"If-None-Match": etag},
                {"If-Modified-Since": "Fri, 01 Jan 2100 00:00:00 GMT"},
            ]:
                status, conditional_headers, body = request(base, path, headers={**selection, **validator})
                check(scenario + " cache validates generated bytes " + path + " " + next(iter(validator)), status == 304 and body == b"" and "no-store" in conditional_headers.get("Cache-Control", "").lower())
                status, conditional_headers, body = request(base, path, method="HEAD", headers={**selection, **validator})
                check(scenario + " cache conditional HEAD is bodyless " + path + " " + next(iter(validator)), status == 304 and body == b"" and "no-store" in conditional_headers.get("Cache-Control", "").lower())
            status, _, body = request(base, path, headers={**selection, "If-None-Match": '"changed"', "If-Modified-Since": "Fri, 01 Jan 2100 00:00:00 GMT"})
            check("ETag takes precedence over dates " + path, status == 200 and body == expected[path])

    status, headers, body = request(base, "/ordinary/")
    check("ordinary WordPress page remains available", status == 200 and headers.get_content_type() == "text/html" and b"CACHE-FAILURE-CONTENT" in body)
    print(f"Cache-failure HTTP: {failures} failures", flush=True)
    return bool(failures)


def main():
    """Run one disposable worker group and clean up on every exit path."""
    existing = os.environ.get("KNTNT_CACHE_FAILURE_HTTP_BASE")
    if existing:
        return probe(existing.rstrip("/"))
    directory = Path(__file__).resolve().parent
    root = str(directory.parent.parent)
    base = "http://127.0.0.1:" + os.environ.get("KNTNT_CACHE_FAILURE_PORT", "9440")
    command = [
        "npx", "--yes", "@wp-playground/cli@3.1.36", "server",
        "--php=8.4", "--wp=latest", "--workers=1",
        "--port=" + base.rsplit(":", 1)[1], "--site-url=" + base,
        "--mount=" + root + ":/wordpress/wp-content/plugins/kntnt-ai-visibility",
        "--blueprint=" + str(directory / "cache-failure-blueprint.json"),
    ]
    worker = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, start_new_session=True)
    output = []
    reader = threading.Thread(target=lambda: output.extend(worker.stdout), daemon=True)
    reader.start()
    print("Playground cache-failure worker process group: " + str(worker.pid), flush=True)
    try:
        cleanup = os.environ.get("KNTNT_SESSION_CLEANUP_SCRIPT")
        if cleanup:
            subprocess.run(["uv", "run", cleanup, "add", "pid", str(worker.pid), "ticket #20 disposable Playground cache-failure worker"], check=True)
        deadline = time.monotonic() + 180
        while worker.poll() is None and time.monotonic() < deadline:
            try:
                response = request(base, "/?cache_failure_fixture=fixture-only&action=ready")
                if response[0] == 200 and "php" in json.loads(response[2]):
                    return probe(base)
            except (OSError, ValueError):
                pass
            time.sleep(0.5)
        print("".join(output))
        print("Playground fixture did not become ready; raise the runtime obstacle to the maintainer.", file=sys.stderr)
        return 1
    finally:
        try:
            os.killpg(worker.pid, signal.SIGTERM)
        except ProcessLookupError:
            pass
        try:
            worker.wait(timeout=10)
        except subprocess.TimeoutExpired:
            os.killpg(worker.pid, signal.SIGKILL)
            worker.wait()
        reader.join(timeout=2)


if __name__ == "__main__":
    sys.exit(main())
