<?php
/**
 * Value object carrying one generated artifact's bytes and metadata.
 *
 * A provider's generate() returns an Artifact: the raw bytes plus the content
 * type and last-modified time the serve layer needs to emit correct headers.
 * It is deliberately free of HTTP and caching concerns — the router and the
 * request handler turn it into a response (docs/adr/0007, docs/adr/0008).
 *
 * @package Kntnt\Ai_Visibility
 * @since   0.1.0
 */

declare( strict_types = 1 );

namespace Kntnt\Ai_Visibility\Core\Artifact;

/**
 * The generated bytes of a discoverable artifact, with serve metadata.
 *
 * @since 0.1.0
 */
final readonly class Artifact {

	/**
	 * Wraps generated bytes with their serve metadata.
	 *
	 * @since 0.1.0
	 *
	 * @param string $bytes         The artifact's raw body bytes.
	 * @param string $content_type  The MIME type, e.g. 'text/markdown; charset=utf-8'.
	 * @param int    $last_modified Unix timestamp of the artifact's last change.
	 */
	public function __construct(
		public string $bytes,
		public string $content_type,
		public int $last_modified,
	) {}

}
